// Next.js のエントリーポイント
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/app/globals.css';
import Sidebar from '@/components/layout/Sidebar';
import Header from '@/components/layout/Header';
import Providers from '@/components/Providers';

// フォントの設定
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});
// ↓のように生成される
// .font-geist-sans {
//   --font-geist-sans: 'Geist Variable', sans-serif;
// }

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// タイトルの設定
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// <html> など外枠を作る
// ここに Header / Sidebar / Footer を配置する
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ハイドレーションの不一致による警告を許容
    <html lang="ja" suppressHydrationWarning>
      {/* フォントをCSS変数に登録する */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground antialiased`}
      >
        <Providers>
          {/* サイドバーとメインを横に並べる */}
          <div className="bg-muted flex h-screen">
            {/* サイドバー */}
            <Sidebar filterStatus="all" filterCategory="all" />

            {/* ヘッダーとメインを縦に並べる */}
            <div className="flex flex-1 flex-col overflow-hidden">
              <Header></Header>
              <main
                className="flex-1 overflow-y-auto"
                // flex-1: 余白を埋める
                // overflow-y-auto: 縦方向にスクロール可
              >
                {/* page.tsx が入る */}
                {children}
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
